- hosts: localhost
  # gather_facts: false
  connection: local

  tasks:
  - name: Add stable chart repo
    kubernetes.core.helm_repository:
      name: bitnami
      repo_url: "https://kubernetes.github.io/ingress-nginx"


- hosts: localhost
  # gather_facts: false
  connection: local

  tasks:
  - name: Add stable chart repo
    kubernetes.core.helm_repository:
      name: bitnami123
      repo_url: "https://charts.bitnami.com/bitnami"

  tags: second play


- name: My play
  hosts: localhost
  tasks:
  - name: My task
    debug:
      msg: "Doing something"
  tags:
  - tag1
  - tag2
